<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Thippeswamy" failures="1" tests="4" name="Admin_module.Create_cat_to_insert_generic" time="25.749" errors="0" timestamp="2024-04-15T10:09:41 IST" skipped="3">
  <testcase classname="Admin_module.Create_cat_to_insert_generic" name="insert_TO_order" time="9.296">
    <skipped/>
  </testcase> <!-- insert_TO_order -->
  <system-out/>
  <testcase classname="Admin_module.Create_cat_to_insert_generic" name="insert_TO_order" time="5.970">
    <skipped/>
  </testcase> <!-- insert_TO_order -->
  <system-out/>
  <testcase classname="Admin_module.Create_cat_to_insert_generic" name="insert_TO_order" time="5.366">
    <skipped/>
  </testcase> <!-- insert_TO_order -->
  <system-out/>
  <testcase classname="Admin_module.Create_cat_to_insert_generic" name="insert_TO_order" time="5.117">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Admin_module.Create_cat_to_insert_generic.insert_TO_order(Create_cat_to_insert_generic.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- insert_TO_order -->
  <system-out/>
</testsuite> <!-- Admin_module.Create_cat_to_insert_generic -->
